enabled_locales: ["en", "vi"]
client:
  host: "localhost:3000"
users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  gravatar_for:
    size: 80
remember: "1"
not_remember: "0"
per_page: "25"
gravatar_for:
  size: 50
